# Change to true for Disqus comments
disqus:
  comments: false

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'All Posts', path: 'menu', url: "all_posts.html"}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Written on'
